name: daily

on:
  schedule:
    # Runs daily at a weird time (03:17 UTC) to avoid delays during periods of
    # high loads of GitHub Actions workflow runs.
    - cron: '17 3 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and test all modified packages
        id: test
        run: scripts/test/test_install.ps1 -all
      - name: Display log warnings and errors
        if: always()
        run: Select-String "ERR|WARN" -CaseSensitive -Context 0,5 C:\ProgramData\_VM\log.txt
      - name: Upload chocolatey logs to artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: logs-${{ matrix.os }}.zip
          path: |
            C:\ProgramData\chocolatey\logs\chocolatey.log
            C:\ProgramData\chocolatey\lib-bad\**\tools\install_log.txt
            C:\ProgramData\_VM\log.txt
