name: daily

on:
  workflow_dispatch:
  schedule:
    # Runs daily at a weird time (03:17 UTC) to avoid delays during periods of
    # high loads of GitHub Actions workflow runs.
    - cron: '17 3 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # Updating the wiki fails if between the checkout of the wiki and the push of the update the other job pushes its update
      max-parallel: 1
      matrix:
        os: [windows-2019, windows-2022]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and test all packages
        id: test
        run: scripts/test/test_install.ps1 -all
      - name: Display log warnings and errors
        if: always()
        run: if (Test-Path -Path C:\ProgramData\_VM\log.txt ) { Select-String "ERR|WARN" -CaseSensitive -Context 0,5 C:\ProgramData\_VM\log.txt }
      - name: Checkout wiki code
        if: always()
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
      - name: Add results to wiki
        if: always()
        run: python scripts/utils/generate_daily_results.py ${{ github.repository }} ${{ github.sha }} ${{ github.run_number }} ${{ github.run_id }} ${{ matrix.os }}
      - name: Commit changes
        if: always()
        run: |
          cd wiki
          git config user.email 'vm-packages@mandiant.com'
          git config user.name 'vm-packages'
          git commit -am 'Add daily results'
          git push
      - name: Upload chocolatey logs to artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: logs-${{ matrix.os }}.zip
          path: |
            C:\ProgramData\chocolatey\logs\chocolatey.log
            C:\ProgramData\chocolatey\lib-bad\**\tools\install_log.txt
            C:\ProgramData\_VM\log.txt
